### ISSUE TITLE
Biography- Gilberto Rios

### ISSUE THREAD

**Issue by Chanchipeep** [nuestrojardinacademy/nuestrojardinacademy.github.io#10]
Gilberto Rios graduated as elementary school teacher from Instituto Nacional Mixto Alejandro Cordova in his native Guatemala. He later obtained a Master’s degree from the University of San Carlos of Guatemala in Pedagogía y Ciencias en Educación. He both taught and was a school Principal at a primary school in Guatemala until 2000 when he decided to move to the United States.
  
Gilberto loves working with children, enjoys singing, dancing, reading stories to them, and seeing how much learning occurs when children are playing. In these 28 years as an educator, he has learned that connecting with children and really listening to them is key to helping them learn. For Gilberto, reaching children in their formative years is very important to him, so that they grow up to be happy and well rounded individuals. 

Before joining Nuestro Jardin, Gilberto worked in the States at Chiquitos School for the Oregon Development Coalition (OCDC) and at The International School Portland. He is excited to teach at Nuestro Jardín and looks forward to getting to know the children and parents of his new community!
![gilberto photo](https://user-images.githubusercontent.com/23289212/50754912-261f3e00-120c-11e9-8c79-24097ebf6ab1.png)

**Comment by apeters** [comment]
fixed in the latest
