### ISSUE TITLE
Mission- things to add (remove things that aren't relevant)

### ISSUE THREAD

**Issue by Chanchipeep** [nuestrojardinacademy/nuestrojardinacademy.github.io#12]
Our mission is to instill in children a true love of learning through exploration, discovery, and inquiry in ways that promote Spanish language acquisition and learning.
Nuestro Jardín is guided by the following core set of beliefs:
- The child is a strong, intelligent, and creative individual with unique qualities.
- Children are  able to construct their own learning,  driven by their own interests.
- Through interactions with others, children form an understanding of themselves, the world, and their place in it.
- Learning (and second language learning) happens when children form warm relationships with teachers, peers, and their environment through interactions with materials, books, music, games, movement, and ideas.
- A rich learning environment is formed in collaboration with children, families, teachers, and the school community.
- A culturally diverse and inclusive environment that respects the unique qualities and beliefs of children, families, and teachers are essential in helping children develop confidence, acceptance, and lifelong habits of the mind

Children deserve a loving and secure environment, one that promotes a sense of wonder and discovery in learning, one that inspires them. 
Our role as teachers is to mentor and guide them,  to observe and listen to their questions, stories, and ideas,  to find what interests them and then provide opportunities for exploration and further investigation.

**Comment by apeters** [comment]
fixed in the latest
