### ISSUE TITLE
Remove the following:

### ISSUE THREAD

**Issue by Chanchipeep** [nuestrojardinacademy/nuestrojardinacademy.github.io#13]
Page: Program
In "Fostering Cultural Awareness," remove: To this end, we integrate culturally-rich activities in our every-day curriculum, and two Fridays per month, we celebrate Día del Patrimonio (Cultural Heritage Day) by immersing ourselves in a culture from a country or region around the world.

In "Events at Nuestro Jardín," remove everything; you can leave the title but take out the content

Take out Everything for 90/10 Immersion model; you can add:
Title: The Immersion Model at Nuestro Jardín
At Nuestro Jardín, children are immersed in Spanish about 90% of the day. Our communicative approach encourages children to be speaking social Spanish from the very first day of school. In addition, the use of our environment (the 3rd teacher) and how children interact with materials, books, teachers, and peers fosters Spanish acquisition and learning. Spanish is learned through music, games, movement, and with the exchange of children's ideas.

**Comment by apeters** [comment]
this is fixed now
