### ISSUE TITLE
Mission statement- home page

### ISSUE THREAD

**Issue by Chanchipeep** [nuestrojardinacademy/nuestrojardinacademy.github.io#14]
Nuestro Jardín Academy is a Spanish immersion, Reggio Emilia inspired preschool for children 3 to 5 years old. 
Our mission is to instill in children a true love of learning through exploration, discovery, and inquiry in ways that promote Spanish language acquisition and learning.
At Nuestro Jardín, we follow children's interests, and we encourage their natural curiosity and creativity to be expressed in many ways, such as through art, music, movement, and language.

**Comment by apeters** [comment]
fixed in the latest
