### ISSUE TITLE
Summer Camps 2019 info

### ISSUE THREAD

**Issue by Chanchipeep** [nuestrojardinacademy/nuestrojardinacademy.github.io#22]
SUMMER CAMPS AT NUESTRO JARDÍN ARE FOR PRESCHOOL-AGED CHILDREN (3-5 YEARS OLD) CHILDREN WHO ARE GOING TO KINDERGARTEN IN FALL 2019 ARE WELCOME TO ATTEND

For 7 weeks throughout the summer months, we will be offering Spanish Immersion Camps with an emphasis on Visual and Performing Arts that focus on specific themes that change every two weeks. Children will also be exposed to lots of materials found in their natural environment and will be encouraged to create with them!
Camps run week to week, so you may register for one or all eight weeks of summer camp. If you register for the 2 sessions of the same theme, you will receive a 10% discount. No prior Spanish experience required.
Sessions
Session 1 – June 17th-21st: Return of the Dinosaurs Week 1
Session 2– June 24th-28th: Return of the Dinosaurs Week 2
Session 3– July 1st-5th (No school on 7/4): Latin Cooking and Flavors Week 1
Session 4– July 8th-12th: Latin Cooking and Flavors Week 2
Session 5– July 15th-19th: Bugs, Bugs, and More Bugs Week 1 
Session 6– July 22nd-26th: Bugs, Bugs, and More Bugs Week 2 
Session 7– July 29th-August 2nd: Inventors, Creators, and Builders
Throughout the summer, children will:
Learn facts and vocabulary specific to the biweekly themes
Explore the artistic possibilities of objects found in nature such as branches, flowers, rocks, and shells.
Explore the qualities of fruits and vegetables to print, dye, build, cook, and create art.
Explore a rich classroom environment filled with a variety of blocks, loose parts, sensorial tables, and children's literature.
Play outdoor water games.
Visual arts focus:
Observational Drawing
Painting
Printmaking
Collage
Clay
Mixed media
Performing arts focus:
Singing in Spanish
Dancing
Improvisation
Hours of Operation/Fees:
Full Day: 8:30*-4:00 - $340 ($272 for July 1-5)
Half Day: 8:30*-12:30 - $250 ($200 for July 1-5)
* Flexible Drop-off is available starting at 8:00 am.

**_If you register for Week 1 and Week 2 of the same camp, (for example, Return of the Dinosaurs Week 1 and Return of the Dinosaurs Week 2, you will receive a 10% discount)._**

LINK TO JOT FORM:
https://form.jotform.com/90625453177157

**Comment by Chanchipeep** [comment]
[Summer Camps_Descriptions_2019.pdf](https://github.com/nuestrojardinacademy/nuestrojardinacademy.github.io/files/2985444/Summer.Camps_Descriptions_2019.pdf)

**Comment by apeters** [comment]
Ok, I added the link to the pdf
