### ISSUE TITLE
Response to COVID-19

### ISSUE THREAD

**Issue by Chanchipeep** [nuestrojardinacademy/nuestrojardinacademy.github.io#25]
RESPONSE TO COVID-19
Nuestro Jardín Academy has been closed since March 13, 2020 in response to the coronavirus pandemic. Our hearts go out to all those who have been impacted by this health crisis in one way or another. We have been closely monitoring the rapidly changing situation of coronavirus and are following guidance of the CDC, the Early Learning Division, and the Oregon Health Authority. 

We are happy to report that we have been approved to reopen as an emergency child care center on September 1st! We look forward to welcoming back our returning families as well as our new families to our community.

We still have some openings in our 3 and 4-year old classrooms and will restart enrollment in a couple of weeks. We are closely monitoring all current conditions and guidelines, and rest assured we are working arduously to return in the safest way possible!

**Comment by apeters** [comment]
added in the latest
