### ISSUE TITLE
Enrollment info

### ISSUE THREAD

**Issue by Chanchipeep** [nuestrojardinacademy/nuestrojardinacademy.github.io#26]
Thank you for your interest in Nuestro Jardín Academy, Spanish Immersion Preschool! 
ENROLLMENT FOR THE 2020-2021 SCHOOL YEAR WILL RESUME THE WEEK OF JULY 27.
Spots in our 3 and 4 year-old classrooms are still available. In keeping with the new state guidelines due to COVID-19, we are limiting our cohorts to 10 children per day, so preference will be given to families seeking full time spots.  Get on our waitlist now, and you will hear back from us soon!
We serve toilet trained children who are 3 to 5 years of age. If you are interested in our program, we suggest you consider getting on our wait list. Families will be informed about enrollment at the end of March.
Our Summer Program is for 7 weeks, and enrollment starts in March; a separate waitlist application form is posted late February.

Enrollment Options
5 days (Monday- Friday): Half or Full Days
3 days (M, W, F): Half or Full Days
2 days (T,Th): Full Days

Tuition 2020-2021 School Year
[Tuition 2020-2021 School Year_website.pdf](https://github.com/nuestrojardinacademy/nuestrojardinacademy.github.io/files/4921322/Tuition.2020-2021.School.Year_website.pdf)

Newly enrolled students - last month’s tuition and a $275 enrollment fee (non-refundable and subject to change).
Returning students - $175 annual fee due at time of re-enrollment (non-refundable and subject to change).
Sibling Discount:
5% credit is given to a child whose sibling is enrolled during the same school year (not combined with other discounts). Discount applies to 2nd or 3rd sibling.
Advance Tuition Discount:
A tuition discount is available if then entire year is paid in full prior to August 1.
Please note that a 6-9% tuition increase will be assessed each year
WAIT LIST – How it works: We do not charge a fee for families to get in our wait list. Interested families just need to fill out a wait list application. Your child’s place is determined by the date we receive your waitlist form and type of enrollment you are requesting. However, siblings of children currently enrolled or who have been enrolled in our school in the past are given priority. Families are notified via email when a space is available for their child. Parents will have 48 hours to notify us of their decision. They will then have a week to complete the enrollment forms, and pay the deposit and fees. We will regularly assess openings available and use the wait list to inform families when availability exists.
It is very important to keep us up to date with changes to contact details (such as email address and phone numbers).

**Comment by apeters** [comment]
updated in the latest
