### ISSUE TITLE
Erica Ryan Bio

### ISSUE THREAD

**Issue by Chanchipeep** [nuestrojardinacademy/nuestrojardinacademy.github.io#5]
Erica was born in Beaverton, Oregon. Her first trip to Mexico was at the age of 5 to visit her great grandmother who had moved down to Los Barriles, Baja California Sur, Mexico, around the year Erica was born. After her first visit to Mexico, Erica went down with her family every winter and summer vacation to visit her great grandmother.

At the age of 13, Erica's family decided to move down to Mexico permanently. The small town Erica and her family moved to was very Americanized and actually most of the population of the town were retired Americans. Erica had picked up on Spanish over the years on her visits, but she did not become bilingual until the age of 16. She went over to Tlaquepaque, Guadalajara for two months with her stepmother, where there was no tv and no radio in English nor were there any English speaking people around her. This was the first time Erica was fully immersed in the Hispanic culture. 

Erica eventually made a life in Mexico. She got married and had a son in 2010. Erica loved Mexico, but she missed her other family, friends, and all the different things her home town of Oregon had to offer. The biggest thing that motivated Erica is that she was unhappy with the jobs she had worked at over the years and wanted to further her education.

Early 2015, Erica moved back to Oregon. She since decided she not only wanted a job but a career. Through her experience with Hispanic culture, Spanish language, becoming a mother, and raising her son to also be bilingual, she realized she had a passion being around kids and speaking the Spanish language! She also had a passion to have a career where she could be a positive figure and give back.

Erica is attending Portland Community College furthering her education and hopes to one day become a Spanish teacher to pre-k/ kindergarten kids.

**Comment by apeters** [comment]
I need a photo before I can add Erica's bio
