### ISSUE TITLE
Biography- Hannah Graner

### ISSUE THREAD

**Issue by Chanchipeep** [nuestrojardinacademy/nuestrojardinacademy.github.io#9]
Originally from Cochabamba, Bolivia, Hannah Graner brings with her a mutli-cultural perspective in all her works.  Growing up, Hannah spent time in both rural and urban Cochabamba, socializing and understanding the socio-economic differences that divided her home and the country at large.  
This perspective guided her towards her studies in California, where she received her BA in Society and Environment from University of California, Berkeley.  Shortly thereafter, Hannah moved to Portland, where she has re-discovered her passion for children’s education and their role in transforming our society.  
She is grateful to have the opportunity to guide the little ones at Nuestro Jardín Academy and is equally grateful for all they teach her.

**Comment by apeters** [comment]
left NJA
